# Generated by Django 2.2.7 on 2019-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_auto_20191110_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
