# Generated by Django 2.2.7 on 2019-11-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_auto_20191117_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='login_time',
        ),
    ]
