# Generated by Django 2.2.7 on 2019-12-07 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dl', '0008_auto_20191124_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('PRACTICE', 'PRACTICE'), ('LECTURE', 'LECTURE')], max_length=16)),
                ('room', models.IntegerField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Courses')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Groups')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Teacher')),
            ],
            options={
                'db_table': 'studproc',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='files')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('week', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Courses')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
