# Generated by Django 2.2.7 on 2019-12-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0010_auto_20191207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Teacher'),
        ),
    ]
