# Generated by Django 2.2.7 on 2019-12-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0011_auto_20191208_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('info', models.TextField(max_length=300)),
                ('file', models.FileField(upload_to='files/tasks')),
                ('week', models.IntegerField()),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Courses')),
                ('groups', models.ManyToManyField(to='dl.Groups')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
