# Generated by Django 2.2.7 on 2019-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0012_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='files/tasks'),
        ),
    ]
