# Generated by Django 2.2.7 on 2019-12-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0013_auto_20191209_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesForTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Courses')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Groups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Task')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.Teacher')),
            ],
            options={
                'db_table': 'task_grades',
            },
        ),
    ]
