# Generated by Django 2.2.7 on 2019-12-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0015_studentfilesfortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfilesfortask',
            name='file',
            field=models.FileField(blank=True, upload_to='files/student'),
        ),
    ]
